#!/bin/bash
echo "instaling dependency"
echo " "
composer install

read -p "Update dependency ? (Y/n) : " update
if [[ $update == "Y" ]]; then
echo " "
echo "Updateting dependency"
echo " "
composer update
fi

sleep 5s
echo " "
echo "copying dependency to public"
echo " "
bash copyvendor

sleep 5s
read -p "buat file env baru ? (Y/n) : " envbaru
if [[ $envbaru == "Y" ]]; then
echo " "
echo "copying env"
echo " "
cp env .env
fi